baseURL = "http://rancher.xtplayer.cn:8888"
languageCode = "en-us"
title = "Rancher Labs"
theme = "rancher-website-theme"
themesDir = "node_modules"
pluralizeListTitles = false

enableRobotsTXT = true

[permalinks]
  inside-pages = "/:filename/"

[[menu.main]]
identifier = "what-is-rancher"
name       = "认识 Rancher"
weight     = "1"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "概述"
  url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/overview/"
  parent     = "what-is-rancher"
  weight     = "1"

  [[menu.main]]
  name       = "What Rancher Adds to Kubernetes"
  url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/what-rancher-adds-to-kubernetes/"
  parent     = "what-is-rancher"
  weight     = "2"

  [[menu.main]]
  name       = "Rancher与众不同"
  url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/how-is-rancher-different/"
  parent     = "what-is-rancher"
  weight     = "3"


  [[menu.main]]
  name       = "Run Kubernetes Anywhere"
  url        = "http://rancher.xtplayer.cn:8888/kubernetes/"
  parent     = "what-is-rancher"
  weight     = "4"

  [[menu.main]]
   # name       = "Cluster Operations"
   # url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/cluster-operations/"
   # parent     = "what-is-rancher"
   # weight     = "5"

  [[menu.main]]
   # name       = "Hybrid cloud & multi-cloud"
   # url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/hybrid-multi-cloud/"
   # parent     = "what-is-rancher"
   # weight     = "6"

  [[menu.main]]
   # name       = "Security & compliance"
   # url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/security-and-compliance/"
   # parent     = "what-is-rancher"
   # weight     = "7"

  [[menu.main]]
   # name       = "Workload Management"
   # url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/workload-management/"
   # parent     = "what-is-rancher"
   # weight     = "8"

  [[menu.main]]
   # name       = "100% Open Source"
   # url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/open-source/"
   # parent     = "what-is-rancher"
   # weight     = "9"


[[menu.main]]
identifier = "products"
name       = "产品"
weight     = "2"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Rancher"
  url        = "http://rancher.xtplayer.cn:8888/what-is-rancher/overview/"
  parent     = "products"

  [[menu.main]]
  name       = "RancherOS"
  url        = "http://rancher.xtplayer.cn:8888/rancher-os/"
  parent     = "products"


[[menu.main]]
#identifier = "customers"
#name       = "Customers"
#url        = "http://rancher.xtplayer.cn:8888/customers/"
#weight     = "3"

[[menu.main]]
identifier = "learn"
name       = "学习"
weight     = "4"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "博客"
  url        = "http://rancher.xtplayer.cn:8888/blog/"
  parent     = "learn"

  [[menu.main]]
  name       = "文档-中文"
  url        = "http://rancher.xtplayer.cn:8888/docs-cn/"
  parent     = "learn"

  [[menu.main]]
  name       = "文档-英文"
  url        = "http://rancher.xtplayer.cn:8888/docs-en/"
  parent     = "learn"

  [[menu.main]]
  name       = "培训"
  url        = "http://rancher.xtplayer.cn:8888/training/"
  parent     = "learn"

  [[menu.main]]
  name       = "论坛"
  url        = "https://forums.cnrancher.com/"
  target = "_blank"
  pre        = "<i class='material-icons text-sm'>launch</i>"
  parent     = "learn"

  [[menu.main]]
  #name       = "Learning Resources"
  #url        = "http://rancher.xtplayer.cn:8888/learning-resources/"
  #parent     = "learn"

  [[menu.main]]
  name       = "活动"
  url        = "http://rancher.xtplayer.cn:8888/events/"
  parent     = "learn"


[[menu.main]]
identifier = "about"
name       = "关于"
url        = "http://rancher.xtplayer.cn:8888/about/"
weight     = "5"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "相关新闻"
  url        = "http://rancher.xtplayer.cn:8888/news/"
  parent     = "about"

  [[menu.main]]
  name       = "关于我们"
  url        = "http://rancher.xtplayer.cn:8888/about/"
  parent     = "about"

  [[menu.main]]
  name       = "招聘信息"
  url        = "http://rancher.xtplayer.cn:8888/careers/"
  parent     = "about"

  [[menu.main]]
  name       = "联系我们"
  url        = "http://rancher.xtplayer.cn:8888/contact/"
  parent     = "about"

  [[menu.main]]
  name       = "合作伙伴"
  url        = "http://rancher.xtplayer.cn:8888/partners/"
  parent     = "about"





#footer menu#
[[menu.footer]]
identifier = "about"
pre = "<i class='material-icons'>info_outline</i>"
name       = "关于"
url        = "http://rancher.xtplayer.cn:8888/about/"

[[menu.footer]]
identifier = "contact"
pre = "<i class='material-icons'>chat_bubble_outline</i>"
name       = "联系我们"
url        = "http://rancher.xtplayer.cn:8888/contact/"

[[menu.footer]]
identifier = "privacy"
pre = "<i class='material-icons'>fingerprint</i>"
name       = "隐私"
url        = "http://rancher.xtplayer.cn:8888/privacy/"

[[menu.footer]]
identifier = "careers"
pre = "<i class='material-icons'>people_outline</i>"
name       = "招聘信息"
url        = "http://rancher.xtplayer.cn:8888/careers/"
